### ISSUE TITLE
problem importing create connection

### ISSUE THREAD

**Issue by Warren3013** [rayhan0x01/nodejs-websocket-sqli#1]
![image](https://user-images.githubusercontent.com/53001575/210963793-595f0794-96d5-417a-82e2-134713628a7d.png)
Hi

I am getting the below error please can you let me know what could be the cause.

**Comment by rayhan0x01** [comment]
You have a file named `websocket.py` on the same directory that's colliding with the actual `websocket` module import. Change the filename, and it should fix the issue.
